version: '3'
services:
  node-app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - PORT=4000
    env_file:
      - ./.env
    command: npm run dev
  postgres-runner:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=abcduser
      - POSTGRES_PASSWORD=abcdpsw
    volumes:
      - /home/sree/Documents/Works/naadanvipani/pg-files/:/var/lib/postgresql/data